In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\josam\OneDrive\Desktop\TAHMO-Solar-Radiation-Prediction\TAHMO-Solar-Radiation-Prediction\weather_EO_integrated.csv")
df.head()

C:\Users\josam\AppData\Local\Temp\ipykernel_13148\880526659.py:4: DtypeWarning: Columns (18: EO_timestamp) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\josam\OneDrive\Desktop\TAHMO-Solar-Radiation-Prediction\TAHMO-Solar-Radiation-Prediction\weather_EO_integrated.csv")

,ID,timestamp,precipitation (mm),radiation (W/m2),relativehumidity (-),temperature (degrees Celsius),station,station_name,country,installation_height,...,latitude,longitude,hour,minute,month,day_of_year,gap,EO_timestamp,EO_radiation,EO_match_found
0,b90ca874_2016-01_D3J06S,2016-01-11 10:30:00,0.0,806.0,0.58,20.4,TA00078,Nyandarua High School,KE,2.5,...,-0.200178,36.376936,10,30,1,11,NaN,NaN,NaN,False
1,b90ca874_2016-01_CICFMD,2016-01-11 10:45:00,0.0,612.0,0.58,20.5,TA00078,Nyandarua High School,KE,2.5,...,-0.200178,36.376936,10,45,1,11,0 days 00:15:00,NaN,NaN,False
2,b90ca874_2016-01_7YYUCC,2016-01-11 11:00:00,0.0,775.0,0.55,20.4,TA00078,Nyandarua High School,KE,2.5,...,-0.200178,36.376936,11,0,1,11,0 days 00:15:00,NaN,NaN,False
3,b90ca874_2016-01_GC3UW6,2016-01-11 11:15:00,0.0,379.0,0.56,20.5,TA00078,Nyandarua High School,KE,2.5,...,-0.200178,36.376936,11,15,1,11,0 days 00:15:00,NaN,NaN,False
4,b90ca874_2016-01_DJLS3P,2016-01-11 11:30:00,0.0,405.0,0.58,19.7,TA00078,Nyandarua High School,KE,2.5,...,-0.200178,36.376936,11,30,1,11,0 days 00:15:00,NaN,NaN,False

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 642175 entries, 0 to 642174
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   ID                             642175 non-null  str
 1   timestamp                      642175 non-null  str
 2   precipitation (mm)             642175 non-null  float64
 3   radiation (W/m2)               642175 non-null  float64
 4   relativehumidity (-)           642175 non-null  float64
 5   temperature (degrees Celsius)  642175 non-null  float64
 6   station                        642175 non-null  str
 7   station_name                   642175 non-null  str
 8   country                        642175 non-null  str
 9   installation_height            642175 non-null  float64
 10  elevation                      642175 non-null  float64
 11  latitude                       642175 non-null  float64
 12  longitude                      642175 non-null  float64
 13  hour                           642175 non-null  int64
 14  minute                         642175 non-null  int64
 15  month                          642175 non-null  int64
 16  day_of_year                    642175 non-null  int64
 17  gap                            642135 non-null  str
 18  EO_timestamp                   592813 non-null  str
 19  EO_radiation                   592813 non-null  float64
 20  EO_match_found                 642175 non-null  bool
dtypes: bool(1), float64(9), int64(4), str(7)
memory usage: 98.6 MB

In [3]:
df.dropna(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 592776 entries, 16659 to 609470
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   ID                             592776 non-null  str
 1   timestamp                      592776 non-null  str
 2   precipitation (mm)             592776 non-null  float64
 3   radiation (W/m2)               592776 non-null  float64
 4   relativehumidity (-)           592776 non-null  float64
 5   temperature (degrees Celsius)  592776 non-null  float64
 6   station                        592776 non-null  str
 7   station_name                   592776 non-null  str
 8   country                        592776 non-null  str
 9   installation_height            592776 non-null  float64
 10  elevation                      592776 non-null  float64
 11  latitude                       592776 non-null  float64
 12  longitude                      592776 non-null  float64
 13  hour                           592776 non-null  int64
 14  minute                         592776 non-null  int64
 15  month                          592776 non-null  int64
 16  day_of_year                    592776 non-null  int64
 17  gap                            592776 non-null  str
 18  EO_timestamp                   592776 non-null  str
 19  EO_radiation                   592776 non-null  float64
 20  EO_match_found                 592776 non-null  bool
dtypes: bool(1), float64(9), int64(4), str(7)
memory usage: 95.5 MB

In [4]:
df.describe()

,precipitation (mm),radiation (W/m2),relativehumidity (-),temperature (degrees Celsius),installation_height,elevation,latitude,longitude,hour,minute,month,day_of_year,EO_radiation
count,592776.000000,592776.000000,592776.000000,592776.000000,592776.0,592776.000000,592776.000000,592776.000000,592776.000000,592776.000000,592776.000000,592776.000000,592776.000000
mean,0.084974,192.046702,0.667109,25.806043,2.0,519.260229,4.055360,10.957731,11.521013,22.502581,6.440342,180.832942,231.542820
std,4.306294,282.916286,0.263279,5.424054,0.0,445.521849,9.344757,19.651231,6.921396,16.770388,3.187817,96.615010,309.473881
min,0.000000,0.000000,0.000000,4.100000,2.0,10.000000,-15.763918,-8.195493,0.000000,0.000000,1.000000,3.000000,0.000000
25%,0.000000,0.000000,0.483000,22.500000,2.0,281.000000,-0.093210,-6.018243,6.000000,15.000000,3.000000,87.000000,0.000000
50%,0.000000,0.000000,0.727000,25.600000,2.0,368.000000,5.778639,-0.996417,12.000000,30.000000,7.000000,189.000000,10.500000
75%,0.000000,340.000000,0.892000,29.300000,2.0,542.000000,11.852760,34.970907,18.000000,45.000000,9.000000,262.000000,463.880000
max,256.021000,1427.000000,1.000000,42.900000,2.0,1657.000000,14.494610,39.582155,23.000000,45.000000,11.000000,334.000000,1134.550000

## Fixing the data structure

### Rebuild station IDs, Add the year column, and sort by station_id and timestamp

In [5]:
df['station_id'] = df.groupby(['latitude', 'longitude']).ngroup()
df["year"] = pd.to_datetime(df['timestamp']).dt.year
df['station_id'] = df['station_id'].astype('category')
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

df = df.sort_values(['station_id', 'timestamp']).reset_index(drop=True)

In [6]:
print(df.duplicated(['station_id', 'timestamp']).sum())

0

### Check the 15-minute grid for gaps per station

In [7]:
step = df.groupby('station_id')['timestamp'].diff()
gaps = step[step > pd.Timedelta('15min')]
print(gaps.describe())               
print(gaps.value_counts().head(10))

span = df.groupby('station_id')['timestamp'].agg(['min', 'max', 'count'])
span['expected'] = (span['max'] - span['min']) / pd.Timedelta('15min') + 1
span['completeness'] = span['count'] / span['expected']
print(span.sort_values('completeness').head(10))

count                        363
mean     15 days 04:16:01.983471
std      15 days 00:25:24.320485
min              0 days 00:30:00
25%              0 days 01:00:00
50%             28 days 00:15:00
75%             30 days 00:15:00
max             31 days 13:30:00
Name: timestamp, dtype: object
timestamp
31 days 00:15:00    72
30 days 00:15:00    71
0 days 00:45:00     37
0 days 00:30:00     37
28 days 00:15:00    36
0 days 01:15:00     30
0 days 01:00:00     22
0 days 01:30:00     16
0 days 01:45:00      5
0 days 06:15:00      4
Name: count, dtype: int64
                           min                 max  count  expected  \
station_id
32         2018-01-25 14:00:00 2018-11-30 23:45:00  14994   29704.0
5          2018-01-27 16:45:00 2018-11-30 23:45:00  15101   29501.0
19         2017-01-26 17:45:00 2017-11-30 23:45:00  15193   29593.0
21         2019-01-26 17:15:00 2019-11-30 23:45:00  15195   29595.0
7          2017-01-26 14:15:00 2017-11-30 23:45:00  15207   29607.0
30         2018-01-23 13:45:00 2018-11-30 23:45:00  15406   29897.0
4          2018-01-25 12:00:00 2018-11-30 23:45:00  15312   29712.0
9          2018-01-24 14:15:00 2018-11-30 23:45:00  15399   29799.0
3          2018-01-23 15:15:00 2018-11-30 23:45:00  15491   29891.0
10         2018-01-23 07:00:00 2018-11-30 23:45:00  15516   29924.0

            completeness
station_id
32              0.504781
5               0.511881
19              0.513398
21              0.513431
7               0.513629
30              0.515303
4               0.515347
9               0.516762
3               0.518250
10              0.518514

In [8]:
parts = []
static_cols = ['latitude', 'longitude', 'elevation', 'installation_height']

for sid, g in df.groupby('station_id'):
    g = g.set_index('timestamp')
    full = pd.date_range(g.index.min(), g.index.max(), freq='15min', name='timestamp')
    g = g.reindex(full)
    g['station_id'] = sid
    g[static_cols] = g[static_cols].ffill().bfill()
    g['is_missing'] = g['temperature (degrees Celsius)'].isna()
    parts.append(g.reset_index())

df = pd.concat(parts, ignore_index=True)

# recompute calendar columns for the inserted rows
df['hour'] = df['timestamp'].dt.hour
df['minute'] = df['timestamp'].dt.minute
df['month'] = df['timestamp'].dt.month
df['day_of_year'] = df['timestamp'].dt.dayofyear

In [9]:
df.head()

,timestamp,ID,precipitation (mm),radiation (W/m2),relativehumidity (-),temperature (degrees Celsius),station,station_name,country,installation_height,...,minute,month,day_of_year,gap,EO_timestamp,EO_radiation,EO_match_found,station_id,year,is_missing
0,2018-01-03 00:15:00,eb142cce_2018-01_7W7EUE,0.085,0.0,0.943,18.5,TA00331,Ndirande Secondary School,MW,2.0,...,15,1,3,0 days 00:15:00,2018-01-03 00:00:00,0.0,True,0,2018.0,False
1,2018-01-03 00:30:00,eb142cce_2018-01_I3AJI9,0.000,0.0,0.934,18.4,TA00331,Ndirande Secondary School,MW,2.0,...,30,1,3,0 days 00:15:00,2018-01-03 00:00:00,0.0,True,0,2018.0,False
2,2018-01-03 00:45:00,eb142cce_2018-01_9V2O3C,0.000,0.0,0.942,18.6,TA00331,Ndirande Secondary School,MW,2.0,...,45,1,3,0 days 00:15:00,2018-01-03 01:00:00,0.0,True,0,2018.0,False
3,2018-01-03 01:00:00,eb142cce_2018-01_6KTBT8,0.000,0.0,0.955,18.7,TA00331,Ndirande Secondary School,MW,2.0,...,0,1,3,0 days 00:15:00,2018-01-03 01:00:00,0.0,True,0,2018.0,False
4,2018-01-03 01:15:00,eb142cce_2018-01_IAXCM1,0.000,0.0,0.963,18.6,TA00331,Ndirande Secondary School,MW,2.0,...,15,1,3,0 days 00:15:00,2018-01-03 01:00:00,0.0,True,0,2018.0,False

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1121329 entries, 0 to 1121328
Data columns (total 24 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   timestamp                      1121329 non-null  datetime64[us]
 1   ID                             592776 non-null   str
 2   precipitation (mm)             592776 non-null   float64
 3   radiation (W/m2)               592776 non-null   float64
 4   relativehumidity (-)           592776 non-null   float64
 5   temperature (degrees Celsius)  592776 non-null   float64
 6   station                        592776 non-null   str
 7   station_name                   592776 non-null   str
 8   country                        592776 non-null   str
 9   installation_height            1121329 non-null  float64
 10  elevation                      1121329 non-null  float64
 11  latitude                       1121329 non-null  float64
 12  longitude                      1121329 non-null  float64
 13  hour                           1121329 non-null  int32
 14  minute                         1121329 non-null  int32
 15  month                          1121329 non-null  int32
 16  day_of_year                    1121329 non-null  int32
 17  gap                            592776 non-null   str
 18  EO_timestamp                   592776 non-null   str
 19  EO_radiation                   592776 non-null   float64
 20  EO_match_found                 592776 non-null   object
 21  station_id                     1121329 non-null  int64
 22  year                           592776 non-null   float64
 23  is_missing                     1121329 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(10), int32(4), int64(1), object(1), str(6)
memory usage: 180.7+ MB

In [11]:
df.columns

Index(['timestamp', 'ID', 'precipitation (mm)', 'radiation (W/m2)',
       'relativehumidity (-)', 'temperature (degrees Celsius)', 'station',
       'station_name', 'country', 'installation_height', 'elevation',
       'latitude', 'longitude', 'hour', 'minute', 'month', 'day_of_year',
       'gap', 'EO_timestamp', 'EO_radiation', 'EO_match_found', 'station_id',
       'year', 'is_missing'],
      dtype='str')

### Preciptation handling

In [12]:
orig = df.loc[~df['is_missing']]

# 1. Native time step per station
step = orig.groupby('station_id')['timestamp'].diff()
native = step.groupby(orig['station_id']).agg(lambda s: s.mode().iat[0])
print(native.value_counts())            # how many stations are really 15-min?

timestamp
0 days 00:15:00    37
Name: count, dtype: int64

In [13]:
# 2. Share missing per station
print(df.groupby('station_id')['is_missing'].mean().describe())

count    37.000000
mean      0.471237
std       0.013135
min       0.429907
25%       0.463256
50%       0.471297
75%       0.481486
max       0.495219
Name: is_missing, dtype: float64

In [14]:
# 3. Length of the missing runs
df = df.sort_values(['station_id', 'timestamp'])
chg = df['is_missing'].ne(df.groupby('station_id')['is_missing'].shift())
runs = df.groupby(chg.cumsum()).agg(
    miss=('is_missing', 'first'), n=('is_missing', 'size'))
miss = runs[runs['miss']]
bins = pd.cut(miss['n'], [0, 4, 24, 96, 672, 10**7],
              labels=['<=1h', '<=6h', '<=1d', '<=1wk', '>1wk'])
print(miss.groupby(bins, observed=True)['n'].agg(['count', 'sum']))   # runs and rows

      count     sum
n
<=1h    126     297
<=6h     48     532
<=1d      6     323
>1wk    183  527401

In [15]:
df = df.sort_values(['station_id', 'timestamp']).reset_index(drop=True)

chg = df['is_missing'].ne(df.groupby('station_id')['is_missing'].shift())
run_len = df.groupby(chg.cumsum())['is_missing'].transform('size')
df = df.loc[~(df['is_missing'] & (run_len > 96))].copy()

step = df.groupby('station_id')['timestamp'].diff()
df['segment_id'] = (step.isna() | (step != pd.Timedelta('15min'))).cumsum()

g = df.groupby('segment_id')
df['temp_lag_1h'] = g['temperature (degrees Celsius)'].shift(4)
df['temp_roll_6h_mean'] = (g['temperature (degrees Celsius)']
                           .rolling(24, min_periods=12).mean()
                           .reset_index(level=0, drop=True))

In [16]:
seg = df.groupby('segment_id').agg(
    station=('station_id', 'first'), start=('timestamp', 'min'),
    end=('timestamp', 'max'), rows=('timestamp', 'size'))
seg['days'] = (seg['end'] - seg['start']).dt.total_seconds() / 86400

print(seg['days'].describe())
print(seg[seg['station'] == seg['station'].iloc[0]])   # one station's blocks
print(df['gap'].value_counts().head())                 # may already label these

count    220.000000
mean      28.111174
std        6.370481
min        4.291667
25%       29.989583
50%       29.989583
75%       30.989583
max       30.989583
Name: days, dtype: float64
            station               start                 end  rows       days
segment_id
1                 0 2018-01-03 00:15:00 2018-01-31 23:45:00  2783  28.979167
2                 0 2018-03-01 00:00:00 2018-03-31 23:45:00  2976  30.989583
3                 0 2018-05-01 00:00:00 2018-05-31 23:45:00  2976  30.989583
4                 0 2018-07-01 00:15:00 2018-07-31 22:00:00  2968  30.906250
5                 0 2018-09-01 00:00:00 2018-09-30 23:45:00  2880  29.989583
6                 0 2018-11-01 00:00:00 2018-11-30 23:45:00  2880  29.989583
gap
0 days 00:15:00     592408
31 days 00:15:00        72
30 days 00:15:00        71
0 days 00:30:00         39
0 days 00:45:00         38
Name: count, dtype: int64

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 593928 entries, 0 to 1121328
Data columns (total 27 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   timestamp                      593928 non-null  datetime64[us]
 1   ID                             592776 non-null  str
 2   precipitation (mm)             592776 non-null  float64
 3   radiation (W/m2)               592776 non-null  float64
 4   relativehumidity (-)           592776 non-null  float64
 5   temperature (degrees Celsius)  592776 non-null  float64
 6   station                        592776 non-null  str
 7   station_name                   592776 non-null  str
 8   country                        592776 non-null  str
 9   installation_height            593928 non-null  float64
 10  elevation                      593928 non-null  float64
 11  latitude                       593928 non-null  float64
 12  longitude                      593928 non-null  float64
 13  hour                           593928 non-null  int32
 14  minute                         593928 non-null  int32
 15  month                          593928 non-null  int32
 16  day_of_year                    593928 non-null  int32
 17  gap                            592776 non-null  str
 18  EO_timestamp                   592776 non-null  str
 19  EO_radiation                   592776 non-null  float64
 20  EO_match_found                 592776 non-null  object
 21  station_id                     593928 non-null  int64
 22  year                           592776 non-null  float64
 23  is_missing                     593928 non-null  bool
 24  segment_id                     593928 non-null  int64
 25  temp_lag_1h                    591896 non-null  float64
 26  temp_roll_6h_mean              590603 non-null  float64
dtypes: bool(1), datetime64[us](1), float64(12), int32(4), int64(2), object(1), str(6)
memory usage: 113.8+ MB

In [18]:
df.isna().sum()

timestamp                           0
ID                               1152
precipitation (mm)               1152
radiation (W/m2)                 1152
relativehumidity (-)             1152
temperature (degrees Celsius)    1152
station                          1152
station_name                     1152
country                          1152
installation_height                 0
elevation                           0
latitude                            0
longitude                           0
hour                                0
minute                              0
month                               0
day_of_year                         0
gap                              1152
EO_timestamp                     1152
EO_radiation                     1152
EO_match_found                   1152
station_id                          0
year                             1152
is_missing                          0
segment_id                          0
temp_lag_1h                      2032
temp_roll_6h_mean                3325
dtype: int64

In [19]:
df.dropna(inplace=True)

In [20]:
df.drop("installation_height", axis=1, inplace=True) # its std=0

In [21]:
df.columns

Index(['timestamp', 'ID', 'precipitation (mm)', 'radiation (W/m2)',
       'relativehumidity (-)', 'temperature (degrees Celsius)', 'station',
       'station_name', 'country', 'elevation', 'latitude', 'longitude', 'hour',
       'minute', 'month', 'day_of_year', 'gap', 'EO_timestamp', 'EO_radiation',
       'EO_match_found', 'station_id', 'year', 'is_missing', 'segment_id',
       'temp_lag_1h', 'temp_roll_6h_mean'],
      dtype='str')

In [22]:
p, rh, rad = 'precipitation (mm)', 'relativehumidity (-)', 'radiation (W/m2)'

print(df[p].describe(percentiles=[.9, .99, .999, .9999]))
for t in [5, 10, 20, 30, 50, 100]:
    print(f'> {t} mm:', (df[p] > t).sum())

count     589840.000000
mean           0.085307
std            4.316857
min            0.000000
90%            0.000000
99%            0.170000
99.9%          3.281000
99.99%       255.238274
max          256.021000
Name: precipitation (mm), dtype: float64
> 5 mm: 345
> 10 mm: 195
> 20 mm: 179
> 30 mm: 174
> 50 mm: 174
> 100 mm: 172

In [23]:
big = df.loc[df[p] > 30, ['station_id', 'timestamp', p, rh, rad,
                          'temperature (degrees Celsius)']]
print(big.sort_values(p, ascending=False).head(30))
print(big['station_id'].value_counts())               # one faulty station?
print(big.groupby(big['timestamp'].dt.date).size())   # one bad day?

        station_id           timestamp  precipitation (mm)  \
546800          18 2017-03-26 03:15:00             256.021
540756          18 2017-01-22 04:15:00             255.987
546799          18 2017-03-26 03:00:00             255.970
540758          18 2017-01-22 04:45:00             255.953
540763          18 2017-01-22 06:00:00             255.953
546076          18 2017-03-18 14:15:00             255.936
540754          18 2017-01-22 03:45:00             255.919
540759          18 2017-01-22 05:00:00             255.919
540755          18 2017-01-22 04:00:00             255.902
540762          18 2017-01-22 05:45:00             255.868
540760          18 2017-01-22 05:15:00             255.868
540777          18 2017-01-22 09:30:00             255.851
540757          18 2017-01-22 04:30:00             255.834
540761          18 2017-01-22 05:30:00             255.817
540765          18 2017-01-22 06:30:00             255.817
546823          18 2017-03-26 09:00:00             255.817
546815          18 2017-03-26 07:00:00             255.732
540753          18 2017-01-22 03:30:00             255.732
540752          18 2017-01-22 03:15:00             255.715
546798          18 2017-03-26 02:45:00             255.715
546065          18 2017-03-18 11:30:00             255.698
546797          18 2017-03-26 02:30:00             255.681
540738          18 2017-01-21 23:45:00             255.630
540766          18 2017-01-22 06:45:00             255.613
540747          18 2017-01-22 02:00:00             255.596
540767          18 2017-01-22 07:00:00             255.579
540746          18 2017-01-22 01:45:00             255.545
540740          18 2017-01-22 00:15:00             255.545
546811          18 2017-03-26 06:00:00             255.545
540737          18 2017-01-21 23:30:00             255.545

        relativehumidity (-)  radiation (W/m2)  temperature (degrees Celsius)
546800                 0.994               0.0                           23.7
540756                 0.993               0.0                           21.2
546799                 0.999               0.0                           23.6
540758                 0.997               0.0                           21.2
540763                 0.998               0.0                           21.1
546076                 0.521               0.0                           34.6
540754                 0.992               0.0                           21.4
540759                 1.000               0.0                           21.1
540755                 0.995               0.0                           21.3
540762                 0.992               0.0                           21.1
540760                 1.000               0.0                           21.1
540777                 0.998             453.0                           25.1
540757                 0.990               0.0                           21.3
540761                 1.000               0.0                           20.9
540765                 0.994               2.0                           21.1
546823                 1.000               0.0                           27.1
546815                 0.998               0.0                           24.5
540753                 0.994               0.0                           21.3
540752                 0.999               0.0                           21.4
546798                 0.998               0.0                           23.7
546065                 0.598               0.0                           33.8
546797                 0.999               0.0                           23.8
540738                 0.986               0.0                           21.6
540766                 1.000              11.0                           21.0
540747                 0.985               0.0                           21.6
540767                 0.998              34.0                           21.1
540746                 0.984               0.0                           21.6
540740                 0.985               0.0                           21.7
546811                 0.995               0.0                           24.0
540737                 0.980               0.0                           21.6
station_id
18    174
Name: count, dtype: int64
timestamp
2017-01-21    16
2017-01-22    42
2017-01-24     1
2017-03-18    19
2017-03-23    36
2017-03-25    18
2017-03-26    41
2017-05-25     1
dtype: int64

In [24]:
row = big.sort_values(p, ascending=False).iloc[0]
ts, sid = row['timestamp'], row['station_id']

# same station, +-1 hour
print(df[(df.station_id == sid) &
         df.timestamp.between(ts - pd.Timedelta('1h'), ts + pd.Timedelta('1h'))]
        [['timestamp', p, rh, rad]])

# all stations at that moment
print(df.loc[df.timestamp == ts, p].describe())

                 timestamp  precipitation (mm)  relativehumidity (-)  \
546796 2017-03-26 02:15:00             255.374                 0.992
546797 2017-03-26 02:30:00             255.681                 0.999
546798 2017-03-26 02:45:00             255.715                 0.998
546799 2017-03-26 03:00:00             255.970                 0.999
546800 2017-03-26 03:15:00             256.021                 0.994
546801 2017-03-26 03:30:00             253.740                 0.998
546802 2017-03-26 03:45:00             253.757                 0.990
546803 2017-03-26 04:00:00             254.013                 0.998
546804 2017-03-26 04:15:00             254.149                 0.998

        radiation (W/m2)
546796               0.0
546797               0.0
546798               0.0
546799               0.0
546800               0.0
546801               0.0
546802               0.0
546803               0.0
546804               0.0
count      7.000000
mean      36.574429
std       96.766842
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max      256.021000
Name: precipitation (mm), dtype: float64

In [25]:
g = df.groupby('segment_id')[p]
neighbour_max = pd.concat([g.shift(1), g.shift(-1)], axis=1).max(axis=1).fillna(0)
share_wet = (df[p] > 0.1).groupby(df['timestamp']).transform('mean')

isolated = (df[p] > 30) & (neighbour_max < 1) & (share_wet < 0.1)

df['precip_suspect'] = df[p] > 30
df['precip_spike_removed'] = isolated
df.loc[isolated, p] = np.nan

In [26]:
cap = df[p].quantile(0.9999)               # or a fixed physical cap you choose
df['precip_clipped'] = df[p].clip(upper=cap)
df['log_precip'] = np.log1p(df['precip_clipped'])
df['rain_flag'] = (df[p] > 0.1).astype('int8')

🌧️ Precipitation Cleaning Breakdown
| Part | What it does |
|---|---|
| `p, rh, rad = ...` | Creates shortcuts for column names |
| `describe()` | Shows rainfall statistics: mean, std, percentiles, max |
| `df[p] > 5, 10, 20...` | Counts how many rainfall values exceed each threshold |
| `big = ... > 30` | Collects unusually high rainfall values for investigation |
| `sort_values().head(30)` | Shows the 30 highest rainfall values |
| `value_counts()` | Checks if one station produces most extreme values |
| `groupby(date)` | Checks if extreme values are concentrated on one day |
| `±1 hour` | Checks rainfall before and after the suspicious value |
| `all stations at timestamp` | Checks whether other stations also recorded rain at that time |
| `shift(1), shift(-1)` | Gets the previous and next rainfall values |
| `neighbour_max` | Finds the maximum rainfall among the previous/next values |
| `share_wet` | Percentage of stations recording rain at the same time |
| `isolated` | Detects suspicious spikes: `>30 mm` + neighbors `<1 mm` + `<10%` stations raining |
| `precip_suspect` | Flags all rainfall values above 30 mm |
| `precip_spike_removed` | Flags spikes identified as suspicious |
| `np.nan` | Removes suspicious values by marking them as missing |
| `quantile(0.9999)` | Finds the 99.99th percentile as an upper limit |
| `clip()` | Limits extreme values to that upper limit |
| `log1p()` | Compresses large values to reduce their impact on the model |
| `rain_flag` | Converts rainfall into binary: `0 = no rain`, `1 = rain` |

### Cyclic Encoding

In [27]:
# Month: use a 12-month cycle
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

# Day of year: use a full 365-day cycle
df['doy_sin'] = np.sin(2 * np.pi * df['day_of_year'] / 365)
df['doy_cos'] = np.cos(2 * np.pi * df['day_of_year'] / 365)

In [28]:
df[['month_sin', 'month_cos', 'doy_sin', 'doy_cos']].head()

    month_sin  month_cos  doy_sin   doy_cos
11        0.5   0.866025  0.05162  0.998667
12        0.5   0.866025  0.05162  0.998667
13        0.5   0.866025  0.05162  0.998667
14        0.5   0.866025  0.05162  0.998667
15        0.5   0.866025  0.05162  0.998667

## Data Engineering

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 589840 entries, 11 to 1121328
Data columns (total 35 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   timestamp                      589840 non-null  datetime64[us]
 1   ID                             589840 non-null  str
 2   precipitation (mm)             589840 non-null  float64
 3   radiation (W/m2)               589840 non-null  float64
 4   relativehumidity (-)           589840 non-null  float64
 5   temperature (degrees Celsius)  589840 non-null  float64
 6   station                        589840 non-null  str
 7   station_name                   589840 non-null  str
 8   country                        589840 non-null  str
 9   elevation                      589840 non-null  float64
 10  latitude                       589840 non-null  float64
 11  longitude                      589840 non-null  float64
 12  hour                           589840 non-null  int32
 13  minute                         589840 non-null  int32
 14  month                          589840 non-null  int32
 15  day_of_year                    589840 non-null  int32
 16  gap                            589840 non-null  str
 17  EO_timestamp                   589840 non-null  str
 18  EO_radiation                   589840 non-null  float64
 19  EO_match_found                 589840 non-null  object
 20  station_id                     589840 non-null  int64
 21  year                           589840 non-null  float64
 22  is_missing                     589840 non-null  bool
 23  segment_id                     589840 non-null  int64
 24  temp_lag_1h                    589840 non-null  float64
 25  temp_roll_6h_mean              589840 non-null  float64
 26  precip_suspect                 589840 non-null  bool
 27  precip_spike_removed           589840 non-null  bool
 28  precip_clipped                 589840 non-null  float64
 29  log_precip                     589840 non-null  float64
 30  rain_flag                      589840 non-null  int8
 31  month_sin                      589840 non-null  float64
 32  month_cos                      589840 non-null  float64
 33  doy_sin                        589840 non-null  float64
 34  doy_cos                        589840 non-null  float64
dtypes: bool(3), datetime64[us](1), float64(17), int32(4), int64(2), int8(1), object(1), str(6)
memory usage: 137.3+ MB

In [30]:
df.columns

Index(['timestamp', 'ID', 'precipitation (mm)', 'radiation (W/m2)',
       'relativehumidity (-)', 'temperature (degrees Celsius)', 'station',
       'station_name', 'country', 'elevation', 'latitude', 'longitude', 'hour',
       'minute', 'month', 'day_of_year', 'gap', 'EO_timestamp', 'EO_radiation',
       'EO_match_found', 'station_id', 'year', 'is_missing', 'segment_id',
       'temp_lag_1h', 'temp_roll_6h_mean', 'precip_suspect',
       'precip_spike_removed', 'precip_clipped', 'log_precip', 'rain_flag',
       'month_sin', 'month_cos', 'doy_sin', 'doy_cos'],
      dtype='str')

In [31]:
df['relativehumidity (-)'].values

array([0.974, 0.98 , 0.98 , ..., 0.72 , 0.744, 0.729], shape=(589840,))

In [32]:
df = df.sort_values(['station_id', 'timestamp']).reset_index(drop=True)

In [33]:
df.head()

,timestamp,ID,precipitation (mm),radiation (W/m2),relativehumidity (-),temperature (degrees Celsius),station,station_name,country,elevation,...,temp_roll_6h_mean,precip_suspect,precip_spike_removed,precip_clipped,log_precip,rain_flag,month_sin,month_cos,doy_sin,doy_cos
0,2018-01-03 03:00:00,eb142cce_2018-01_1B4HSH,0.0,0.0,0.974,19.0,TA00331,Ndirande Secondary School,MW,1139.632,...,18.725000,False,False,0.0,0.0,0,0.5,0.866025,0.05162,0.998667
1,2018-01-03 03:15:00,eb142cce_2018-01_BZQA4D,0.0,0.0,0.980,18.9,TA00331,Ndirande Secondary School,MW,1139.632,...,18.738462,False,False,0.0,0.0,0,0.5,0.866025,0.05162,0.998667
2,2018-01-03 03:30:00,eb142cce_2018-01_Y1YG6A,0.0,6.0,0.980,18.9,TA00331,Ndirande Secondary School,MW,1139.632,...,18.750000,False,False,0.0,0.0,0,0.5,0.866025,0.05162,0.998667
3,2018-01-03 03:45:00,eb142cce_2018-01_M3NFB3,0.0,23.0,0.985,19.0,TA00331,Ndirande Secondary School,MW,1139.632,...,18.766667,False,False,0.0,0.0,0,0.5,0.866025,0.05162,0.998667
4,2018-01-03 04:00:00,eb142cce_2018-01_E2D9EP,0.0,28.0,0.989,19.1,TA00331,Ndirande Secondary School,MW,1139.632,...,18.787500,False,False,0.0,0.0,0,0.5,0.866025,0.05162,0.998667

## TIME FEATURES

In [34]:
import pvlib

# Time of day in decimal hours
tod = df['hour'] + df['minute'] / 60

# Local solar time
solar_tod = (tod + df['longitude'] / 15) % 24

df['solar_tod_sin'] = np.sin(
    2 * np.pi * solar_tod / 24
)
df['solar_tod_cos'] = np.cos(
    2 * np.pi * solar_tod / 24
)

## 3. SOLAR / RADIATION FEATURES

In [35]:
df = df.reset_index()

In [36]:
df.columns

Index(['index', 'timestamp', 'ID', 'precipitation (mm)', 'radiation (W/m2)',
       'relativehumidity (-)', 'temperature (degrees Celsius)', 'station',
       'station_name', 'country', 'elevation', 'latitude', 'longitude', 'hour',
       'minute', 'month', 'day_of_year', 'gap', 'EO_timestamp', 'EO_radiation',
       'EO_match_found', 'station_id', 'year', 'is_missing', 'segment_id',
       'temp_lag_1h', 'temp_roll_6h_mean', 'precip_suspect',
       'precip_spike_removed', 'precip_clipped', 'log_precip', 'rain_flag',
       'month_sin', 'month_cos', 'doy_sin', 'doy_cos', 'solar_tod_sin',
       'solar_tod_cos'],
      dtype='str')

In [37]:
df['timestamp'].head()

0   2018-01-03 03:00:00
1   2018-01-03 03:15:00
2   2018-01-03 03:30:00
3   2018-01-03 03:45:00
4   2018-01-03 04:00:00
Name: timestamp, dtype: datetime64[us]

In [38]:
# Clear-sky index
df['clear_sky_index'] = np.where(
    df['EO_radiation'] > 0,
    df['radiation (W/m2)'] / df['EO_radiation'],
    np.nan
)

df['clear_sky_index'] = df[
    'clear_sky_index'
].clip(0, 1.2)


# Solar position
solar_position = pvlib.solarposition.get_solarposition(
    time=df['timestamp'],
    latitude=df['latitude'],
    longitude=df['longitude']
)

df['solar_zenith'] = solar_position['zenith'].values

df['is_daylight'] = (
    df['solar_zenith'] < 90
).astype(int)

g = df.groupby('station_id', group_keys=False)

# Rolling clear-sky index
df['csi_roll_1h'] = (
    df.groupby('station_id')
      .rolling('1h', on='timestamp')['clear_sky_index']
      .mean()
      .reset_index(level=0, drop=True)
      .reset_index(drop=True)
)

df['csi_roll_3h'] = (
    df.groupby('station_id')
      .rolling('3h', on='timestamp')['clear_sky_index']
      .mean()
      .reset_index(level=0, drop=True)
      .reset_index(drop=True)
)

## 5. THERMODYNAMIC FEATURES

In [39]:
T = df['temperature (degrees Celsius)']
RH = df['relativehumidity (-)'].clip(0.01, 1)

# RH is assumed to be between 0 and 1
RH_percent = RH * 100

# Magnus formula
a = 17.62
b = 243.12

gamma = (
    np.log(RH_percent / 100)
    + (a * T) / (b + T)
)

df['dew_point'] = (
    b * gamma / (a - gamma)
)

# Dew point depression
df['dew_point_depression'] = T - df['dew_point']


# Vapor pressure (hPa)
df['vapor_pressure'] = (
    6.112
    * np.exp((17.67 * T) / (T + 243.5))
    * RH
)


# Temperature normalized to sea level
df['temperature_sea_level'] = (
    T + 0.0065 * df['elevation']
)

## 6. LAGS

In [40]:
lag_steps = {
    '15m': 1,
    '1h': 4,
    '3h': 12,
    '6h': 24,
    '24h': 96
}

lag_columns = {
    'temperature (degrees Celsius)': 'temp',
    'relativehumidity (-)': 'rh',
    'radiation (W/m2)': 'radiation',
    'clear_sky_index': 'csi'
}

for col, prefix in lag_columns.items():

    for name, steps in lag_steps.items():

        df[f'{prefix}_lag_{name}'] = (
            g[col]
            .shift(steps)
        )

## 7. TENDENCIES / DIFFERENCES

In [41]:
df['temp_change_1h'] = (
    g['temperature (degrees Celsius)'].diff(4)
)

df['rh_change_1h'] = (
    g['relativehumidity (-)'].diff(4)
)

df['radiation_change_1h'] = (
    g['radiation (W/m2)'].diff(4)
)

df['csi_change_1h'] = (
    g['clear_sky_index'].diff(4)
)

## 8. ROLLING WEATHER FEATURES

In [42]:
rolling_windows = {
    '1h': 4,
    '6h': 24,
    '24h': 96
}

weather_columns = {
    'temperature (degrees Celsius)': 'temp',
    'relativehumidity (-)': 'rh',
    'radiation (W/m2)': 'radiation'
}

df = df.sort_values(
    ['station_id', 'timestamp']
).reset_index(drop=True)


for col, prefix in weather_columns.items():

    for name, window in rolling_windows.items():

        grouped = df.groupby('station_id')[col]

        df[f'{prefix}_roll_{name}_mean'] = (
            grouped
            .transform(
                lambda x: x.rolling(
                    window,
                    min_periods=1
                ).mean()
            )
        )

        df[f'{prefix}_roll_{name}_std'] = (
            grouped
            .transform(
                lambda x: x.rolling(
                    window,
                    min_periods=1
                ).std()
            )
        )

        df[f'{prefix}_roll_{name}_min'] = (
            grouped
            .transform(
                lambda x: x.rolling(
                    window,
                    min_periods=1
                ).min()
            )
        )

        df[f'{prefix}_roll_{name}_max'] = (
            grouped
            .transform(
                lambda x: x.rolling(
                    window,
                    min_periods=1
                ).max()
            )
        )

## 9. PRECIPITATION FEATURES

In [43]:
precip_windows = {
    '1h': 4,
    '6h': 24,
    '24h': 96
}

for name, window in precip_windows.items():

    df[f'precip_acc_{name}'] = (
        df.groupby('station_id')['precipitation (mm)']
        .transform(
            lambda x: x.rolling(
                window,
                min_periods=1
            ).sum()
        )
    )


df['rain_count_24h'] = (
    df.groupby('station_id')['rain_flag']
    .transform(
        lambda x: x.rolling(
            96,
            min_periods=1
        ).sum()
    )
)

rain_time = df['timestamp'].where(
    df['rain_flag'] == 1
)

last_rain = (
    rain_time
    .groupby(df['station_id'])
    .ffill()
)

df['time_since_rain_hours'] = (
    (
        df['timestamp'] - last_rain
    ).dt.total_seconds()
    / 3600
)

## 10. DAILY FEATURES

In [44]:
df['temp_same_time_yesterday'] = (
    g['temperature (degrees Celsius)']
    .shift(96)
)

df['rh_same_time_yesterday'] = (
    g['relativehumidity (-)']
    .shift(96)
)

df['radiation_same_time_yesterday'] = (
    g['radiation (W/m2)']
    .shift(96)
)

## 11. TEMPERATURE DAILY RANGE SO FAR

In [45]:
df['date'] = df['timestamp'].dt.date

daily_group = df.groupby(['station_id', 'date'])

df['temp_daily_min_so_far'] = (
    daily_group['temperature (degrees Celsius)']
    .cummin()
)

df['temp_daily_max_so_far'] = (
    daily_group['temperature (degrees Celsius)']
    .cummax()
)

df['temp_daily_range_so_far'] = (
    df['temp_daily_max_so_far']
    - df['temp_daily_min_so_far']
)

C:\Users\josam\AppData\Local\Temp\ipykernel_13148\676720907.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['temp_daily_range_so_far'] = (

## 12. STATION × HOUR × MONTH CLIMATOLOGY

In [46]:

climatology = (
    df.groupby(
        ['station_id', 'hour', 'month']
    )['temperature (degrees Celsius)']
    .mean()
    .rename('temp_climatology')
    .reset_index()
)

df = df.merge(
    climatology,
    on=['station_id', 'hour', 'month'],
    how='left'
)

df['temp_anomaly'] = (
    df['temperature (degrees Celsius)']
    - df['temp_climatology']
)

C:\Users\josam\AppData\Local\Temp\ipykernel_13148\915756353.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['temp_anomaly'] = (

## 13. SPATIAL FEATURES

In [47]:
stations = (
    df[
        ['station_id', 'latitude', 'longitude']
    ]
    .drop_duplicates('station_id')
    .set_index('station_id')
)


# Haversine distance between stations
def haversine(lat1, lon1, lat2, lon2):

    R = 6371.0

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)

    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    return 2 * R * np.arcsin(np.sqrt(a))


# Build nearest-station map
station_ids = stations.index.tolist()

nearest_stations = {}

for station in station_ids:

    lat1 = stations.loc[station, 'latitude']
    lon1 = stations.loc[station, 'longitude']

    distances = []

    for other in station_ids:

        if station == other:
            continue

        lat2 = stations.loc[other, 'latitude']
        lon2 = stations.loc[other, 'longitude']

        distance = haversine(
            lat1, lon1,
            lat2, lon2
        )

        distances.append((other, distance))

    distances.sort(key=lambda x: x[1])

    # k = 5 nearest stations
    nearest_stations[station] = [
        x[0] for x in distances[:5]
    ]

## 14. SAME-TIMESTAMP SPATIAL FEATURES

In [48]:
# Create lookup tables
weather_at_time = df.set_index(
    ['timestamp', 'station_id']
)[
    [
        'temperature (degrees Celsius)',
        'relativehumidity (-)',
        'clear_sky_index'
    ]
]


def spatial_features(row):

    station = row['station_id']
    timestamp = row['timestamp']

    neighbors = nearest_stations.get(station, [])

    values = []

    for neighbor in neighbors:

        try:

            values.append(
                weather_at_time.loc[
                    (timestamp, neighbor)
                ]
            )

        except KeyError:
            pass

    if not values:

        return pd.Series({
            'neighbor_temp_mean': np.nan,
            'neighbor_rh_mean': np.nan,
            'neighbor_csi_mean': np.nan
        })

    values = pd.DataFrame(values)

    return pd.Series({
        'neighbor_temp_mean':
            values['temperature (degrees Celsius)'].mean(),

        'neighbor_rh_mean':
            values['relativehumidity (-)'].mean(),

        'neighbor_csi_mean':
            values['clear_sky_index'].mean()
    })


spatial = df.apply(
    spatial_features,
    axis=1
)

df = pd.concat(
    [df, spatial],
    axis=1
)


# Difference between station and neighbors
df['temp_neighbor_diff'] = (
    df['temperature (degrees Celsius)']
    - df['neighbor_temp_mean']
)

df['rh_neighbor_diff'] = (
    df['relativehumidity (-)']
    - df['neighbor_rh_mean']
)

df['csi_neighbor_diff'] = (
    df['clear_sky_index']
    - df['neighbor_csi_mean']
)

C:\Users\josam\AppData\Local\Temp\ipykernel_13148\2635345668.py:69: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['temp_neighbor_diff'] = (
C:\Users\josam\AppData\Local\Temp\ipykernel_13148\2635345668.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rh_neighbor_diff'] = (
C:\Users\josam\AppData\Local\Temp\ipykernel_13148\2635345668.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['csi_neighbor_diff'] = (

## 15. STATIC STATION FEATURES -> already added

## 16. CLEANUP

In [49]:
df = df.drop(columns=['date'])

# Sort again
df = df.sort_values(
    ['station_id', 'timestamp']
).reset_index(drop=True)


print("Final shape:", df.shape)
print("\nNew features:")
print(df.columns.tolist())

Final shape: (589840, 124)

New features:
['index', 'timestamp', 'ID', 'precipitation (mm)', 'radiation (W/m2)', 'relativehumidity (-)', 'temperature (degrees Celsius)', 'station', 'station_name', 'country', 'elevation', 'latitude', 'longitude', 'hour', 'minute', 'month', 'day_of_year', 'gap', 'EO_timestamp', 'EO_radiation', 'EO_match_found', 'station_id', 'year', 'is_missing', 'segment_id', 'temp_lag_1h', 'temp_roll_6h_mean', 'precip_suspect', 'precip_spike_removed', 'precip_clipped', 'log_precip', 'rain_flag', 'month_sin', 'month_cos', 'doy_sin', 'doy_cos', 'solar_tod_sin', 'solar_tod_cos', 'clear_sky_index', 'solar_zenith', 'is_daylight', 'csi_roll_1h', 'csi_roll_3h', 'dew_point', 'dew_point_depression', 'vapor_pressure', 'temperature_sea_level', 'temp_lag_15m', 'temp_lag_3h', 'temp_lag_6h', 'temp_lag_24h', 'rh_lag_15m', 'rh_lag_1h', 'rh_lag_3h', 'rh_lag_6h', 'rh_lag_24h', 'radiation_lag_15m', 'radiation_lag_1h', 'radiation_lag_3h', 'radiation_lag_6h', 'radiation_lag_24h', 'csi_lag_15m', 'csi_lag_1h', 'csi_lag_3h', 'csi_lag_6h', 'csi_lag_24h', 'temp_change_1h', 'rh_change_1h', 'radiation_change_1h', 'csi_change_1h', 'temp_roll_1h_mean', 'temp_roll_1h_std', 'temp_roll_1h_min', 'temp_roll_1h_max', 'temp_roll_6h_std', 'temp_roll_6h_min', 'temp_roll_6h_max', 'temp_roll_24h_mean', 'temp_roll_24h_std', 'temp_roll_24h_min', 'temp_roll_24h_max', 'rh_roll_1h_mean', 'rh_roll_1h_std', 'rh_roll_1h_min', 'rh_roll_1h_max', 'rh_roll_6h_mean', 'rh_roll_6h_std', 'rh_roll_6h_min', 'rh_roll_6h_max', 'rh_roll_24h_mean', 'rh_roll_24h_std', 'rh_roll_24h_min', 'rh_roll_24h_max', 'radiation_roll_1h_mean', 'radiation_roll_1h_std', 'radiation_roll_1h_min', 'radiation_roll_1h_max', 'radiation_roll_6h_mean', 'radiation_roll_6h_std', 'radiation_roll_6h_min', 'radiation_roll_6h_max', 'radiation_roll_24h_mean', 'radiation_roll_24h_std', 'radiation_roll_24h_min', 'radiation_roll_24h_max', 'precip_acc_1h', 'precip_acc_6h', 'precip_acc_24h', 'rain_count_24h', 'time_since_rain_hours', 'temp_same_time_yesterday', 'rh_same_time_yesterday', 'radiation_same_time_yesterday', 'temp_daily_min_so_far', 'temp_daily_max_so_far', 'temp_daily_range_so_far', 'temp_climatology', 'temp_anomaly', 'neighbor_temp_mean', 'neighbor_rh_mean', 'neighbor_csi_mean', 'temp_neighbor_diff', 'rh_neighbor_diff', 'csi_neighbor_diff']

In [50]:
df.to_csv("prepared_data_for_modeling.csv", index=False)
print("Saved successfully!")

Saved successfully!